//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCS_1._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCS_1._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///h1{
        ///  font-size: 30px;
        ///  color: #fff;
        ///  text-transform: uppercase;
        ///  font-weight: 300;
        ///  text-align: center;
        ///  margin-bottom: 15px;
        ///}
        ///b{
        ///  font-size: 13px;
        ///  color:white;
        ///}
        ///a:link{
        ///  font-size: 14px;
        ///  color:white;
        ///}
        ///a:hover{
        ///  color:black
        ///}
        ///a:visited{
        ///  color:orange
        ///}
        ///table{
        ///  width:100%;
        ///  table-layout: fixed;
        ///}
        ///.tbl-header{
        ///  background-color: rgba(255,255,255,0.3);
        /// }
        ///.tbl-content{
        ///  height:300px;
        ///  overflow-x:auto;
        ///  margin-top: 0px;
        ///  border: 1px solid rgba(255,255,255,0.3);
        ///}
        ///th{
        ///  padding: 20px 15p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html &gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;title&gt;JCS Report&lt;/title&gt;
        ///  
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css&quot;&gt;
        ///
        ///  
        ///      &lt;link rel=&quot;stylesheet&quot; href=&quot;css/style.css&quot;&gt;
        ///
        ///  
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;section&gt;
        ///  &lt;!--for demo wrap--&gt;
        ///  &lt;h1&gt;Installed Components&lt;/h1&gt;
        ///  &lt;b&gt;Target Url: &lt;/b&gt;&lt;a href=&quot;_site&quot; target=&quot;_blank&quot;&gt;_sName&lt;/a&gt;&lt;br&gt;&lt;/br&gt;
        ///  &lt;div class=&quot;tbl-header&quot;&gt;
        ///    &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; border=&quot;0&quot;&gt;
        ///      &lt;thead&gt;
        ///        &lt;tr&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &apos;.tbl-content&apos; consumed little space for vertical scrollbar, scrollbar width depend on browser/os/platfrom. Here calculate the scollbar width .
        ///$(window).on(&quot;load resize &quot;, function() {
        ///  var scrollWidth = $(&apos;.tbl-content&apos;).width() - $(&apos;.tbl-content table&apos;).width();
        ///  $(&apos;.tbl-header&apos;).css({&apos;padding-right&apos;:scrollWidth});
        ///}).resize();.
        /// </summary>
        internal static string js {
            get {
                return ResourceManager.GetString("js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
